### ISSUE TITLE
Babel not working at all because of an exception

### ISSUE THREAD

**Issue by Achraf-cyber** [nikosportolos/babel#68]
Whenever I run babel no matter the command, I get this error
```> Running command: all
Terminated with exception
    type 'String' is not a subtype of type 'Map<dynamic, dynamic>'
    #0      Loader._parseTranslationFile (package:babel/src/utils/loader.dart:72:53)
    #1      Loader.loadTranslationsFromPath (package:babel/src/utils/loader.dart:53:9)       
    #2      Loader.loadProjectFromPath (package:babel/src/utils/loader.dart:26:21)
    #3      new Babel.fromPath (package:babel/src/babel.dart:27:14)
    #4      ListAllCommand.execute (package:babel/cli/commands/list/all.dart:19:17)
    #5      BaseCommand.run (package:dart_cmder/src/interface/command.dart:137:13)
    <asynchronous suspension>
    #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
    <asynchronous suspension>
    #7      main (file:///C:/Users/HP/AppData/Local/Pub/Cache/hosted/pub.dev/babel-0.0.4-prerelease/bin/babel.dart:10:3)
    <asynchronous suspension>```

**Comment by nikosportolos** [comment]
Hello @Achraf-cyber , thanks for reporting this.
Could you please provide an example of the `.arb` file you are trying to parse and the version of Flutter SDK you are using?

**Comment by Achraf-cyber** [comment]
flutter --version
```Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (5 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3
```

arb file 
```
{
  "@@author": "Someone someone@gmail.com",
  "@@locale": "en",
  "account_exists_with_different_credential": "account exists with the same email. Login with you email",
  "addAnImage": "add an Image",
  "addNew": "Add new",
  "addNewStade": "Add new stade",
  "addOffer": "Add an offer"
}
```
The arb file is translated into french,  arabic && english

**Comment by Achraf-cyber** [comment]
Full output when I run ` babel clean unused-translations` : 
```╭────────────────────────────────────────────────╮
│          ╔═╗   ╔══╗  ╔═╗   ╔══╗  ╦             │
│          ╠═╩╗  ╠══╣  ╠═╩╗  ║═╣   ║             │
│          ╚══╝  ╩  ╩  ╚══╝  ╚══╝  ╩══╝          │
│    Translations management for Flutter apps    │
╰────────────────────────────────────────────────╯
> Running command: unused-translations
Terminated with exception
    type 'String' is not a subtype of type 'Map<dynamic, dynamic>'
    #0      Loader._parseTranslationFile (package:babel/src/utils/loader.dart:72:53)
    #1      Loader.loadTranslationsFromPath (package:babel/src/utils/loader.dart:53:9)
    #2      Loader.loadProjectFromPath (package:babel/src/utils/loader.dart:26:21)
    #3      new Babel.fromPath (package:babel/src/babel.dart:27:14)
    #4      CleanUnusedTranslationsCommand.execute (package:babel/cli/commands/clean/unused.dart:27:17)
    #5      BaseCommand.run (package:dart_cmder/src/interface/command.dart:137:13)
    <asynchronous suspension>
    #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
    <asynchronous suspension>
    #7      main (file:///C:/Users/HP/AppData/Local/Pub/Cache/hosted/pub.dev/babel-0.0.4-prerelease/bin/babel.dart:10:3)
    <asynchronous suspension>
```

**Comment by Achraf-cyber** [comment]
full output when I run ` babel clean` : 
```Unhandled exception:
Missing subcommand for "babel clean".

Usage: babel clean <subcommand> [arguments]
-h, --help          Print this usage information.
-p, --path          The root path of the project where the pubspec.yaml is.
                    (defaults to ".")
-l, --level         Define the level that will be used to filter log messages.
                    [none, verbose, debug, info (default), success, warning, error, fatal]
-d, --logdir        If not null, then messages will be logged into the specified directory.
-c, --[no-]color    If set to false, no colors will be printed in the console.
                    (defaults to on)

Available subcommands:
  generated-files       Deletes all generated localization files.
  unused-translations   Deletes all unused translation keys.

Run "babel help" to see global options.
#0      Command.usageException (package:args/command_runner.dart:466:7)
#1      CommandRunner.runCommand (package:args/command_runner.dart:169:19)
#2      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#3      new Future.sync (dart:async/future.dart:313:27)
#4      CommandRunner.run (package:args/command_runner.dart:122:14)
#5      main (file:///C:/Users/HP/AppData/Local/Pub/Cache/hosted/pub.dev/babel-0.0.4-prerelease/bin/babel.dart:10:21)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
Building package executable... 
Built babel:babel.
Unhandled exception:
Missing subcommand for "babel clean".

Usage: babel clean <subcommand> [arguments]
-h, --help          Print this usage information.
-p, --path          The root path of the project where the pubspec.yaml is.
                    (defaults to ".")
-l, --level         Define the level that will be used to filter log messages.
                    [none, verbose, debug, info (default), success, warning, error, fatal]
-d, --logdir        If not null, then messages will be logged into the specified directory.
-c, --[no-]color    If set to false, no colors will be printed in the console.
                    (defaults to on)

Available subcommands:
  generated-files       Deletes all generated localization files.
  unused-translations   Deletes all unused translation keys.

Run "babel help" to see global options.
#0      Command.usageException (package:args/command_runner.dart:466:7)
#1      CommandRunner.runCommand (package:args/command_runner.dart:169:19)
#2      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122:25)
#3      new Future.sync (dart:async/future.dart:313:27)
#4      CommandRunner.run (package:args/command_runner.dart:122:14)
#5      main (file:///C:/Users/HP/AppData/Local/Pub/Cache/hosted/pub.dev/babel-0.0.4-prerelease/bin/babel.dart:10:21)
#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)```

**Comment by Achraf-cyber** [comment]
This time there is no error
Full output when I run the `babel` command : 
```Usage: babel <command> [arguments]

Global options:
-h, --help    Print this usage information.

Available commands:
  clean   Clean translations-related files
  list    List project translations
  sort    Sorts the translation keys in the arb files of the project.

Run "babel help <command>" for more information about a command.```
